<meta name="theme-color"
      content="#ffffff">
<link rel="apple-touch-icon"
      sizes="180x180"
      href="{{ url('favicons/apple-touch-icon.png') }}">
<link rel="icon"
      type="image/png"
      sizes="32x32"
      href="{{ url('favicons/favicon-32x32.png') }}">
<link rel="icon"
      type="image/png"
      sizes="16x16"
      href="{{ url('favicons/favicon-16x16.png') }}'">
<link rel="manifest"
      href="{{ url('favicons/site.webmanifest') }}">
<link rel="mask-icon"
      href="{{ url('favicons/safari-pinned-tab.svg') }}"
      color="#ff9b00">
<meta name="msapplication-TileColor"
      content="#da532c">
<meta name="theme-color"
      content="#ffffff">
