<?php

namespace App\Containers\UserSection\Authentication\UI\API\Requests;

use App\Containers\UserSection\User\Models\User;
use App\Ship\Data\Rules\OldPasswordRule;
use App\Ship\Parents\Requests\Request as ParentRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Password;

class ResetPasswordRequest extends ParentRequest
{
    /**
     * Define which Roles and/or Permissions has access to this request.
     */
    protected array $access = [
        'permissions' => '',
        'roles' => '',
    ];

    /**
     * Id's that needs decoding before applying the validation rules.
     */
    protected array $decode = [
        // 'id',
    ];

    /**
     * Defining the URL parameters (e.g, `/user/{id}`) allows applying
     * validation rules on them and allows accessing them like request data.
     */
    protected array $urlParameters = [
        // 'id',
    ];

    public function rules(): array
    {
        return [
            'token' => 'required',
            'new_password' => [
                User::getPasswordValidationRules(),
                'required'
            ],
            'password_confirmation' => [
                'required',
                User::getPasswordValidationRules(),
                'same:new_password'
            ],
        ];
    }

    public function messages()
    {
        return [
            'new_password' => 'Пароль должен содержать минимум 6 символов используя английские буквы и цифры',
            'new_password.required' => 'Новый пароль обязателен для заполнения',
            'password.required' => 'Старый пароль обязателен для заполнения',
            'password.current_password' => 'Данный пароль не соответствует вашему действующему паролю',
        ];

        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function authorize(): bool
    {
        return $this->check([
            'hasAccess',
        ]);
    }
}
